# Generated by Django 5.0.14 on 2026-09-01 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.tenant'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['tenant'], name='billing_sub_tenant__7e6f87_idx'),
        ),
    ]
