# Generated by Django 5.0.14 on 2026-09-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='interval',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('ANNUAL', 'Annual')], default='MONTHLY', max_length=10),
        ),
    ]
