# Generated by Django 5.0.14 on 2026-09-08 04:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_plan_razorpay_plan_id_webhookevent'),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCheckout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed')], default='CREATED', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.plan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkout', to='tenants.tenant')),
            ],
        ),
    ]
