# Generated by Django 5.0.14 on 2026-09-08 13:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_out_of_order_guards'),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric', models.CharField(choices=[('active_members', 'Active members')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'metric'], name='billing_usa_tenant__5992ed_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='usagerecord',
            constraint=models.UniqueConstraint(fields=('tenant', 'metric', 'period_start', 'period_end'), name='unique_usage_snapshot'),
        ),
    ]
