# Generated by Django 5.0.14 on 2026-09-08 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_usagerecord'),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProrationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('calculated_at', models.DateTimeField()),
                ('amount_cents', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('from_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.plan')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proration_records', to='billing.subscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proration_records', to='tenants.tenant')),
                ('to_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='billing.plan')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'subscription'], name='billing_pro_tenant__5192dd_idx')],
            },
        ),
    ]
