# Generated by Django 5.0.14 on 2026-09-08 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_prorationrecord'),
        ('tenants', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationDiscrepancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_subscription_id', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('STATUS_MISMATCH', 'Status mismatch'), ('LOCAL_CANCELED_PROVIDER_ACTIVE', 'Locally canceled, still live at provider'), ('PROVIDER_NOT_FOUND', 'Provider has no record')], max_length=40)),
                ('local_status', models.CharField(max_length=20)),
                ('provider_status', models.CharField(blank=True, max_length=20)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('detected_at', models.DateTimeField()),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_discrepancies', to='billing.subscription')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_discrepancies', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'reconciliation discrepancies',
                'indexes': [models.Index(fields=['tenant', 'subscription'], name='billing_rec_tenant__194b0f_idx'), models.Index(fields=['detected_at'], name='billing_rec_detecte_f3f5ff_idx')],
            },
        ),
    ]
