# Generated by Django 5.0.14 on 2026-09-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_reconciliationdiscrepancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_members_per_workspace',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='max_workspaces',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
