# Generated by Django 5.0.14 on 2026-09-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0014_pro_plan_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioncheckout',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='subscriptioncheckout',
            name='session_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
