# Generated by Django 5.0.14 on 2026-09-13 14:21

import apps.properties.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_number', models.CharField(blank=True, max_length=32)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=16)),
                ('currency', models.CharField(max_length=3)),
                ('property_name', models.CharField(max_length=255)),
                ('unit_identifier', models.CharField(max_length=50)),
                ('resident_name', models.CharField(max_length=255)),
                ('resident_email', models.EmailField(max_length=254)),
                ('subtotal_cents', models.BigIntegerField(default=0)),
                ('adjustments_cents', models.BigIntegerField(default=0)),
                ('total_cents', models.BigIntegerField(default=0)),
                ('amount_paid_cents', models.BigIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=500)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='BillCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('AMOUNT_ADJUSTMENT', 'Amount adjustment'), ('READING_CORRECTION', 'Meter reading correction')], max_length=20)),
                ('reason', models.CharField(max_length=500)),
                ('original_values', models.JSONField(default=dict)),
                ('corrected_values', models.JSONField(default=dict)),
                ('amount_delta_cents', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='properties.bill')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=8)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='properties.billingcycle'),
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('monthly_rent_cents', models.PositiveBigIntegerField()),
                ('security_deposit_cents', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='lease',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='properties.lease'),
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter_number', models.CharField(max_length=64)),
                ('utility_type', models.CharField(choices=[('ELECTRICITY', 'Electricity')], default='ELECTRICITY', max_length=16)),
                ('unit_of_measure', models.CharField(default='kWh', max_length=16)),
                ('multiplier', models.DecimalField(decimal_places=4, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('installed_at', models.DateField(blank=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading_date', models.DateField()),
                ('reading_value', models.DecimalField(decimal_places=3, max_digits=14)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual entry'), ('IMPORT', 'Import')], default='MANUAL', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('proof', models.FileField(blank=True, null=True, upload_to=apps.properties.models.reading_proof_path)),
                ('proof_content_type', models.CharField(blank=True, max_length=64)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='properties.meter')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReadingCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_value', models.DecimalField(decimal_places=3, max_digits=14)),
                ('corrected_value', models.DecimalField(decimal_places=3, max_digits=14)),
                ('reason', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='properties.meterreading')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_cents', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('payment_date', models.DateField()),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank transfer'), ('UPI', 'UPI'), ('CARD', 'Card'), ('ONLINE', 'Online'), ('OTHER', 'Other')], max_length=16)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('VOIDED', 'Voided')], default='COMPLETED', max_length=10)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('idempotency_key', models.CharField(blank=True, max_length=64)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=500)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='properties.bill')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='IN', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='tenants.tenant')),
            ],
            options={
                'verbose_name_plural': 'properties',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='properties.property'),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=32)),
                ('issued_at', models.DateTimeField()),
                ('amount_cents', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('resident_name', models.CharField(max_length=255)),
                ('unit_identifier', models.CharField(max_length=50)),
                ('property_name', models.CharField(max_length=255)),
                ('bill_number', models.CharField(blank=True, max_length=32)),
                ('payment_method', models.CharField(max_length=16)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='properties.bill')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receipt', to='properties.payment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('reference', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='residencies', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='properties.resident'),
        ),
        migrations.AddField(
            model_name='lease',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.resident'),
        ),
        migrations.AddField(
            model_name='bill',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='properties.resident'),
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utility_type', models.CharField(choices=[('ELECTRICITY', 'Electricity')], default='ELECTRICITY', max_length=16)),
                ('rate_per_unit_cents', models.DecimalField(decimal_places=4, max_digits=14)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='BillLineItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('RENT', 'Rent'), ('ELECTRICITY', 'Electricity'), ('MAINTENANCE', 'Maintenance'), ('OTHER_CHARGE', 'Other charge'), ('DISCOUNT', 'Discount'), ('ADJUSTMENT', 'Adjustment'), ('LATE_FEE', 'Late fee')], max_length=16)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('unit_price_cents', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('amount_cents', models.BigIntegerField()),
                ('meter_number', models.CharField(blank=True, max_length=64)),
                ('opening_reading_value', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('closing_reading_value', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('opening_reading_date', models.DateField(blank=True, null=True)),
                ('closing_reading_date', models.DateField(blank=True, null=True)),
                ('multiplier', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('units_consumed', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='properties.bill')),
                ('correction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='properties.billcorrection')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='properties.meter')),
                ('closing_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='properties.meterreading')),
                ('opening_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='properties.meterreading')),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='properties.tariff')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=50)),
                ('floor', models.CharField(blank=True, max_length=20)),
                ('unit_type', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('VACANT', 'Vacant'), ('OCCUPIED', 'Occupied'), ('MAINTENANCE', 'Maintenance'), ('INACTIVE', 'Inactive')], default='VACANT', max_length=12)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='properties.property')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
        ),
        migrations.AddField(
            model_name='meter',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meters', to='properties.unit'),
        ),
        migrations.AddField(
            model_name='lease',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='properties.unit'),
        ),
        migrations.AddField(
            model_name='bill',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bills', to='properties.unit'),
        ),
        migrations.CreateModel(
            name='WorkspaceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('next_value', models.PositiveBigIntegerField(default=1)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('receipt_footer', models.CharField(blank=True, max_length=500)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('due_days_after_period_end', models.PositiveSmallIntegerField(default=10)),
                ('default_maintenance_cents', models.PositiveIntegerField(default=0)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='property_settings', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='billingcycle',
            constraint=models.UniqueConstraint(fields=('tenant', 'period_start'), name='unique_cycle_per_month'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['tenant', 'meter', 'reading_date'], name='properties__tenant__207ba1_idx'),
        ),
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.UniqueConstraint(fields=('meter', 'reading_date'), name='unique_reading_per_meter_day'),
        ),
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.CheckConstraint(check=models.Q(('reading_value__gte', 0)), name='reading_value_non_negative'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['tenant', 'is_active'], name='properties__tenant__f72bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='receipt',
            index=models.Index(fields=['tenant', 'issued_at'], name='properties__tenant__a214dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='receipt',
            constraint=models.UniqueConstraint(fields=('tenant', 'receipt_number'), name='unique_receipt_number'),
        ),
        migrations.AddConstraint(
            model_name='resident',
            constraint=models.UniqueConstraint(fields=('tenant', 'user'), name='unique_resident_per_workspace'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['tenant', 'payment_date'], name='properties__tenant__ea38c2_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['bill'], name='properties__bill_id_ecfb3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(check=models.Q(('amount_cents__gt', 0)), name='payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='unique_payment_idempotency_key'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('tenant', 'reference'), name='unique_payment_reference'),
        ),
        migrations.AddConstraint(
            model_name='tariff',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('tenant', 'utility_type', 'effective_from'), name='unique_tariff_start'),
        ),
        migrations.AddConstraint(
            model_name='tariff',
            constraint=models.CheckConstraint(check=models.Q(('rate_per_unit_cents__gte', 0)), name='tariff_rate_non_negative'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['tenant', 'property'], name='properties__tenant__f83432_idx'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('property', 'identifier'), name='unique_unit_per_property'),
        ),
        migrations.AddIndex(
            model_name='meter',
            index=models.Index(fields=['tenant', 'unit'], name='properties__tenant__a21ce3_idx'),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.UniqueConstraint(fields=('tenant', 'meter_number'), name='unique_meter_number'),
        ),
        migrations.AddConstraint(
            model_name='meter',
            constraint=models.CheckConstraint(check=models.Q(('multiplier__gt', 0)), name='meter_multiplier_positive'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['tenant', 'status'], name='properties__tenant__64cf47_idx'),
        ),
        migrations.AddIndex(
            model_name='lease',
            index=models.Index(fields=['resident'], name='properties__residen_401c0d_idx'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('unit',), name='one_active_lease_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='lease',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='lease_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['tenant', 'period_start'], name='properties__tenant__bb7812_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['tenant', 'status'], name='properties__tenant__4e8916_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['tenant', 'due_date'], name='properties__tenant__31dc32_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['resident'], name='properties__residen_24eebe_idx'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('unit', 'resident', 'period_start'), name='unique_bill_per_unit_resident_period'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.UniqueConstraint(condition=models.Q(('bill_number', ''), _negated=True), fields=('tenant', 'bill_number'), name='unique_bill_number'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(check=models.Q(('amount_paid_cents__gte', 0)), name='bill_paid_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(check=models.Q(('amount_paid_cents__lte', models.F('total_cents')), ('amount_paid_cents', 0), _connector='OR'), name='bill_paid_not_above_total'),
        ),
        migrations.AddConstraint(
            model_name='workspacesequence',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_workspace_sequence'),
        ),
    ]
