# Generated by Django 5.0.14 on 2026-09-15 18:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('tenants', '0003_invitation_membership_ended_at_membership_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPaymentWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=20)),
                ('dedupe_key', models.CharField(max_length=64)),
                ('event_type', models.CharField(max_length=64)),
                ('provider_order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('provider_payment_id', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=40)),
                ('processing_error', models.CharField(blank=True, max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='OnlinePaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=20)),
                ('provider_order_id', models.CharField(max_length=45, unique=True)),
                ('provider_order_ref', models.CharField(blank=True, max_length=64)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('payment_session_id', models.TextField(blank=True)),
                ('amount_cents', models.PositiveBigIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACTIVE', 'Awaiting payment'), ('SUCCEEDED', 'Paid'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('UNAPPLIED', 'Needs refund'), ('REFUND_PENDING', 'Refund pending'), ('REFUNDED', 'Refunded')], default='CREATED', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('provider_payment_id', models.CharField(blank=True, max_length=64)),
                ('last_payment_status', models.CharField(blank=True, max_length=20)),
                ('failure_message', models.CharField(blank=True, max_length=255)),
                ('unapplied_reason', models.CharField(blank=True, max_length=40)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('refund_id', models.CharField(blank=True, max_length=40)),
                ('refund_status', models.CharField(blank=True, max_length=20)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_payment_attempts', to='properties.bill')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='online_attempt', to='properties.payment')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='online_payment_attempts', to='properties.resident')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenants.tenant')),
            ],
        ),
        migrations.AddConstraint(
            model_name='propertypaymentwebhookevent',
            constraint=models.UniqueConstraint(fields=('provider', 'dedupe_key'), name='unique_property_webhook_delivery'),
        ),
        migrations.AddIndex(
            model_name='onlinepaymentattempt',
            index=models.Index(fields=['tenant', 'status'], name='properties__tenant__e39008_idx'),
        ),
        migrations.AddIndex(
            model_name='onlinepaymentattempt',
            index=models.Index(fields=['status', 'expires_at'], name='properties__status_6ad273_idx'),
        ),
        migrations.AddConstraint(
            model_name='onlinepaymentattempt',
            constraint=models.CheckConstraint(check=models.Q(('amount_cents__gt', 0)), name='online_attempt_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='onlinepaymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['CREATED', 'ACTIVE'])), fields=('bill',), name='one_open_online_attempt_per_bill'),
        ),
        migrations.AddConstraint(
            model_name='onlinepaymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_payment_id', ''), _negated=True), fields=('provider', 'provider_payment_id'), name='unique_online_provider_payment'),
        ),
    ]
