# Generated by Django 5.0.14 on 2026-09-06 05:35
#
# email-verification-spec.md §4.1: existing rows must be grandfathered as
# verified in the SAME deployable unit that adds the field, not a manual
# follow-up step someone might forget to run. grandfather_existing_users
# below does that — it runs immediately after the AddField in this same
# migration, so every row that existed before this feature shipped comes out
# verified, while User's own field default (False) governs every row created
# from here on.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def grandfather_existing_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.update(email_verified=True)


def noop_reverse(apps, schema_editor):
    # Nothing to undo — reversing this migration drops the column entirely
    # (via AddField's own reverse), so there is no "unverify everyone" state
    # to restore.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(grandfather_existing_users, noop_reverse),
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='users_email_user_id_d4075a_idx')],
            },
        ),
    ]
