# Generated by Django 5.0.14 on 2026-09-13 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing', models.BooleanField(default=True)),
                ('payments', models.BooleanField(default=True)),
                ('membership', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('INVITATION_RECEIVED', 'Invitation received'), ('INVITATION_ACCEPTED', 'Invitation accepted'), ('INVITATION_DECLINED', 'Invitation declined'), ('INVITATION_CANCELLED', 'Invitation cancelled'), ('MEMBER_LEFT', 'Member left'), ('MEMBERSHIP_ENDED', 'Membership ended'), ('BILL_PUBLISHED', 'Bill published'), ('BILL_DUE_SOON', 'Bill due soon'), ('BILL_OVERDUE', 'Bill overdue'), ('BILL_CORRECTED', 'Bill corrected'), ('BILL_CANCELLED', 'Bill cancelled'), ('PAYMENT_RECORDED', 'Payment recorded'), ('PAYMENT_VOIDED', 'Payment voided'), ('RECEIPT_ISSUED', 'Receipt issued'), ('OVERDUE_SUMMARY', 'Overdue summary'), ('CYCLE_INCOMPLETE', 'Billing cycle incomplete'), ('PLAN_LIMIT', 'Plan limit')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body', models.CharField(blank=True, max_length=1000)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, max_length=128, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_564b1f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key__isnull', False)), fields=('recipient', 'dedupe_key'), name='unique_notification_dedupe'),
        ),
    ]
