# Generated by Django 5.0.14 on 2026-09-15 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('INVITATION_RECEIVED', 'Invitation received'), ('INVITATION_ACCEPTED', 'Invitation accepted'), ('INVITATION_DECLINED', 'Invitation declined'), ('INVITATION_CANCELLED', 'Invitation cancelled'), ('MEMBER_LEFT', 'Member left'), ('MEMBERSHIP_ENDED', 'Membership ended'), ('BILL_PUBLISHED', 'Bill published'), ('BILL_DUE_SOON', 'Bill due soon'), ('BILL_OVERDUE', 'Bill overdue'), ('BILL_CORRECTED', 'Bill corrected'), ('BILL_CANCELLED', 'Bill cancelled'), ('PAYMENT_RECORDED', 'Payment recorded'), ('PAYMENT_VOIDED', 'Payment voided'), ('RECEIPT_ISSUED', 'Receipt issued'), ('ONLINE_PAYMENT_UNAPPLIED', 'Online payment needs refund'), ('OVERDUE_SUMMARY', 'Overdue summary'), ('CYCLE_INCOMPLETE', 'Billing cycle incomplete'), ('PLAN_LIMIT', 'Plan limit')], max_length=32),
        ),
    ]
